# Generated by Django 4.2.7 on 2023-12-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rslug', models.SlugField(blank=True, null=True, unique=True)),
                ('rimage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('rname', models.CharField(max_length=100)),
                ('rdescription', models.TextField()),
                ('rcreated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
